apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  # how many pods
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        # label for service to conenct to
        app: nginx-app
    spec:
      containers:
        # name of the app to deploy
        - name: nginx-app-container
        # name of the image
          image: nginx
          ports: 
          # port inside the pods
            - containerPort: 80
        