apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: node-js
  template:
    metadata:
      labels: 
        app: node-js
    spec:
      containers:
        - name: node-js
          image: ${aws_id}.dkr.ecr.${aws_region}.amazonaws.com/${aws_repo}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred